include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # Allowed for this demo, but usually bad
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
